parameters:
  ALGO_PARAMS_CLOSE_ONLY_MODE: False
  ALGO_PARAMS_ENABLED: True
  ALGO_PARAMS_ORDER_LEVEL_SPREAD: 10
  ALGO_PARAMS_ORDER_LEVEL_AMOUNT_PCT: 0.1
  ALGO_PARAMS_ORDER_INSERT_TIME_SEC: 1
  ALGO_PARAMS_REEVAL_TIME_SEC: 1
  ALGO_PARAMS_ORDER_REFRESH_TOLERANCE_PCT: 0.05
  ALGO_PARAMS_PRICE_ADJUSTMENT_BPS: 0
  ALGO_PARAMS_BUY_LEVELS: 3
  ALGO_PARAMS_SELL_LEVELS: 3
  ALGO_PARAMS_BID_SPREAD: 0.01
  ALGO_PARAMS_ASK_SPREAD: 0.01
  ALGO_PARAMS_MINIMUM_SPREAD: 0
  ALGO_PARAMS_ORDER_AMOUNT_USD: 100
  ALGO_PARAMS_GLOBAL_POS_LEAN_BPS_PER_100K_USD: 10
  ALGO_PARAMS_POS_LEAN_BPS_PER_100K_USD: 10
  ALGO_PARAMS_MAX_POSITION_USD: 1000000
  ALGO_PARAMS_TAKER_THRESHOLD_BPS: 2
  ALGO_PARAMS_PRICE_EMA_SEC: 10
  ALGO_PARAMS_FR_EMA_SEC: 260
  ALGO_PARAMS_BASIS_EMA_SEC: 260
  ALGO_PARAMS_MAX_LEVERAGE: 25
  ALGO_PARAMS_MAX_MARGIN_RATIO: 10
  ALGO_PARAMS_EMPTY_BOOK_PENALTY: 1